var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/tools/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__43cfc72f._.js")
R.c("server/chunks/ssr/_e13d30bd._.js")
R.c("server/chunks/ssr/_3c6e99f1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e5701a73._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ccbe6ae2._.js")
R.c("server/chunks/ssr/af9ea_next_dist_f5d2498b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/af9ea_next_dist_client_components_builtin_global-error_a59a19e8.js")
R.c("server/chunks/ssr/[root-of-the-server]__ae6689c7._.js")
R.c("server/chunks/ssr/af9ea_next_dist_client_components_db84ebba._.js")
R.c("server/chunks/ssr/af9ea_next_dist_client_components_builtin_forbidden_f3bcaaa9.js")
R.c("server/chunks/ssr/af9ea_next_dist_client_components_builtin_unauthorized_0f7ce14d.js")
R.c("server/chunks/ssr/_next-internal_server_app_tools_page_actions_3bc858b5.js")
R.m(19805)
module.exports=R.m(19805).exports
