var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__bbf608dc._.js")
R.c("server/chunks/ssr/_caf6fa36._.js")
R.c("server/chunks/ssr/0bac4_next_dist_esm_build_templates_app-page_8c3699ff.js")
R.c("server/chunks/ssr/[root-of-the-server]__ebbdf156._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9d687172._.js")
R.c("server/chunks/ssr/0bac4_next_dist_0cc30004._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ae6689c7._.js")
R.c("server/chunks/ssr/0bac4_next_dist_client_components_88376b30._.js")
R.c("server/chunks/ssr/0bac4_next_dist_client_components_builtin_forbidden_6c1c5203.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_554ec2bf.js")
R.m(52197)
module.exports=R.m(52197).exports
