var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__29eb1a95._.js")
R.c("server/chunks/ssr/_caf6fa36._.js")
R.c("server/chunks/ssr/_75d22357._.js")
R.c("server/chunks/ssr/[root-of-the-server]__31c23c6f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9d687172._.js")
R.c("server/chunks/ssr/0bac4_next_dist_0cc30004._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/0bac4_next_dist_client_components_builtin_global-error_6cf004eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__ae6689c7._.js")
R.c("server/chunks/ssr/0bac4_next_dist_client_components_88376b30._.js")
R.c("server/chunks/ssr/0bac4_next_dist_client_components_builtin_forbidden_6c1c5203.js")
R.c("server/chunks/ssr/0bac4_next_dist_client_components_builtin_unauthorized_6e122128.js")
R.c("server/chunks/ssr/_next-internal_server_app_page_actions_39d4fc33.js")
R.m(88100)
module.exports=R.m(88100).exports
